# Generated by Django 3.0.2 on 2020-07-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cmc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='activity_periods',
            new_name='ActivityPeriods',
        ),
    ]
