# Generated by Django 3.0.2 on 2020-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cmc', '0002_auto_20200703_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
