# Generated by Django 3.0.2 on 2020-07-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cmc', '0003_auto_20200703_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
